apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcollector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcollector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcollector
subjects:
- kind: ServiceAccount
  name: otelcollector
  namespace: hotel
roleRef:
  kind: ClusterRole
  name: otelcollector
  apiGroup: rbac.authorization.k8s.io
