name: search

ports:
  - port: 8082
    targetPort: 8082
 
container:
  command: /go/bin/search
  image:  tanyuzhentyz/hotel
  name: hotel-reserv-search
  ports:
  - containerPort: 8082

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
